DROP TABLE IF EXISTS MEALS;

CREATE TABLE MEALS
(
    ID          INTEGER PRIMARY KEY DEFAULT NEXTVAL('GLOBAL_SEQ'),
    DESCRIPTION VARCHAR(100) NOT NULL,
    CALORIES    INTEGER      NOT NULL,
    DATE_TIME   TIMESTAMP    NOT NULL,
    USER_ID     INTEGER      NOT NULL,
    FOREIGN KEY (USER_ID) REFERENCES USERS (ID) ON DELETE CASCADE
);

CREATE UNIQUE INDEX DATE_TIME_INDEX ON MEALS (DATE_TIME);